### ISSUE TITLE
报错 ./run: line 16: exec: npm: not found

### ISSUE THREAD

**Issue by wdjoys** [hasscc/hass-docker#2]
docker-compose文件
```
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.nju.edu.cn/hasscc/hacn:addons
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Shanghai
      - ALWAYS_INSTALL=true  # 默认为true，每次启动都会逐个预装，否则仅全新HA才会预装
      - ALWAYS_UPGRADE=false # 默认为false，每次启动都会逐个预装最新版本的插件
      - MQTT_USERNAME=homeassistant # 默认为`homeassistant`
      - MQTT_PASSWORD=homeassistant # 默认为空无需授权，推荐设置
      - MQTT_PORT=1883 # 默认为`1883`
      - NODERED_USERNAME=homeassistant # 默认为`homeassistant`
      - NODERED_PASSWORD=homeassistant # Node-Red后台密码
      - NODERED_PORT=1880 # 默认为`1880`
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123 
      - 1883:1883 
      - 1880:1880
    healthcheck:
      test: [CMD-SHELL, curl -I localhost:8123 || exit 1]
```

报错信息
```
root@docker-ubuntu:/mnt/sdb/docker-project/homeassistant# docker compose logs -f --tail=20
homeassistant  | [14:44:48] INFO: Starting Node-RED on port: 1880
homeassistant  | ./run: line 16: exec: npm: not found
homeassistant  | [14:44:49] INFO: Starting Node-RED on port: 1880
homeassistant  | ./run: line 16: exec: npm: not found
homeassistant  | [14:44:50] INFO: Starting Node-RED on port: 1880
homeassistant  | ./run: line 16: exec: npm: not found
homeassistant  | [14:44:51] INFO: Starting Node-RED on port: 1880
homeassistant  | ./run: line 16: exec: npm: not found
homeassistant  | [14:44:52] INFO: Starting Node-RED on port: 1880
homeassistant  | ./run: line 16: exec: npm: not found
homeassistant  | [14:44:53] INFO: Starting Node-RED on po
```

**Comment by al-one** [comment]
已修复，可通过命令`docker compose up -d --pull always`更新镜像。

**Comment by wdjoys** [comment]
添加bemfa集成报错

docker-compose文件，设置了代理
```
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.nju.edu.cn/hasscc/hacn:stable 
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Shanghai


      - HTTP_PROXY=http://192.168.50.254:7893
      - HTTPS_PROXY=http://192.168.50.254:7893
      - NO_PROXY=localhost,127.0.0.1,192.168.50.0/24

      - http_proxy=http://192.168.50.254:7893
      - https_proxy=http://192.168.50.254:7893
      - no_proxy=localhost,127.0.0.1,192.168.50.0/24

      - ALWAYS_INSTALL=true  # 默认为true，每次启动都会逐个预装，否则仅全新HA才会预装
      - ALWAYS_UPGRADE=false # 默认为false，每次启动都会逐个预装最新版本的插件
      - MQTT_USERNAME=homeassistant # 默认为`homeassistant`
      - MQTT_PASSWORD=homeassistant # 默认为空无需授权，推荐设置
      - MQTT_PORT=1883 # 默认为`1883`
      - NODERED_USERNAME=homeassistant # 默认为`homeassistant`
      - NODERED_PASSWORD=homeassistant # Node-Red后台密码
      - NODERED_PORT=1880 # 默认为`1880`
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123 
      - 1883:1883 
      - 1880:1880
    healthcheck:
      test: [CMD-SHELL, curl -I localhost:8123 || exit 1]
```

报错信息

![Image](https://github.com/user-attachments/assets/2168b2f0-130b-4f32-bd6a-013e7c054039)

日志
```
homeassistant  | [12:25:26] INFO: Home Assistant Core finish process exit code 100
homeassistant  | 2025-06-07 20:25:29.534 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.535 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edge_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.536 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tianqi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.536 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration haier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.537 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration terncy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.537 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.538 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.538 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.539 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ha_file_explorer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.539 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ai_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.540 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.540 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.540 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:25:29.541 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bemfa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
homeassistant  | 2025-06-07 20:30:48.162 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package paho-mqtt==1.6.1: × No solution found when resolving dependencies:
homeassistant  |   ╰─▶ Because you require paho-mqtt==1.6.1 and paho-mqtt==2.1.0, we can
homeassistant  |       conclude that your requirements are unsatisfiable.
homeassistant  | 2025-06-07 20:30:48.973 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package paho-mqtt==1.6.1: × No solution found when resolving dependencies:
homeassistant  |   ╰─▶ Because you require paho-mqtt==1.6.1 and paho-mqtt==2.1.0, we can
homeassistant  |       conclude that your requirements are unsatisfiable.
homeassistant  | 2025-06-07 20:30:50.438 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package paho-mqtt==1.6.1: × No solution found when resolving dependencies:
homeassistant  |   ╰─▶ Because you require paho-mqtt==1.6.1 and paho-mqtt==2.1.0, we can
homeassistant  |       conclude that your requirements are unsatisfiable.
homeassistant  | 2025-06-07 20:30:50.439 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.50.201
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
homeassistant  |     resp = await request_handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
homeassistant  |     response = await handler(request)
homeassistant  |                ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
homeassistant  |     result = await handler(request, **request.match_info)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
homeassistant  |     return await func(self, request, *args, **kwargs)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
homeassistant  |     return await method(view, request, data, *args, **kwargs)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 183, in post
homeassistant  |     return await self._post_impl(request, data)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 190, in _post_impl
homeassistant  |     return await super()._post_impl(request, data)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
homeassistant  |     result = await self._flow_mgr.async_init(
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     ...<2 lines>...
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1446, in async_init
homeassistant  |     flow, result = await self._async_init(flow_id, handler, context, data)
homeassistant  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1482, in _async_init
homeassistant  |     flow = await self.async_create_flow(handler, context=context, data=data)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1703, in async_create_flow
homeassistant  |     handler = await _async_get_flow_handler(
homeassistant  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |         self.hass, handler_key, self._hass_config
homeassistant  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |     )
homeassistant  |     ^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3780, in _async_get_flow_handler
homeassistant  |     await _load_integration(hass, domain, hass_config)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3757, in _load_integration
homeassistant  |     await async_process_deps_reqs(hass, hass_config, integration)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 585, in async_process_deps_reqs
homeassistant  |     await requirements.async_get_integration_with_requirements(
homeassistant  |         hass, integration.domain
homeassistant  |     )
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
homeassistant  |     return await manager.async_get_integration_with_requirements(domain)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
homeassistant  |     await future
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
homeassistant  |     await self._async_process_integration(integration, done)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
homeassistant  |     await self.async_process_requirements(
homeassistant  |         integration.domain, integration.requirements
homeassistant  |     )
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
homeassistant  |     await self._async_process_requirements(name, missing)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
homeassistant  |     raise RequirementsNotFound(name, list(failures))
homeassistant  | homeassistant.requirements.RequirementsNotFound: Requirements for bemfa not found: ['paho-mqtt==1.6.1'].
```
